### ISSUE TITLE
RoutingAPIStack high monthly cost on AWS

### ISSUE THREAD

**Issue by lift0xff** [Uniswap/routing-api#187]
Hi! thanks for this excellent piece of software. I have deployed RoutingAPIStack to AWS and am surprised by the relatively high AWS charges. I have $25 in lambda usage fees despite only having used the API for less 100 queries over 6 days.

Specifically, I see the following in my AWS bill:

```
AWS Lambda - Total Compute - US East (Ohio)-Tier-1 | 1,563,577.501 Lambda-GB-Second   USD 26.06
```
If this bill scales w/ actual usage it won't be feasible for me to integrate this API--and Uniswap--with my product. Is there a large upfront cost to setting up the RoutingAPIStack, perhaps upfront caching, or should I expect the cost to scale linearly with my users?

**Comment by lift0xff** [comment]
Any update on this?

**Comment by mikeki** [comment]
The provisioned concurrency is 100 by default, which is what we use for serving our current traffic, but it is likely not the same provisioning that your app needs.

This means that there are 100 Lambdas running at any given time waiting for queries to handle. It sounds like you don't have as much traffic as that, so you could change the configuration to fit your needs.

https://github.com/Uniswap/routing-api/blob/main/bin/app.ts#L187

**Comment by lift0xff** [comment]
> The provisioned concurrency is 100 by default, which is what we use for serving our current traffic, but it is likely not the same provisioning that your app needs.
> 
> This means that there are 100 Lambdas running at any given time waiting for queries to handle. It sounds like you don't have as much traffic as that, so you could change the configuration to fit your needs.
> 
> https://github.com/Uniswap/routing-api/blob/main/bin/app.ts#L187

Thanks! this is super helpful
