### ISSUE TITLE
Set up hardhat mainnet fork to test SwapRouter02 with V2 Router and Swap+Add

### ISSUE THREAD

**Issue by willhennessy** [Uniswap/routing-api#33]
Let's integration test the `SwapRouter02` contract to test if it works with the two features that depend on it:
1. V2 routing in Auto Router
2. Swap + Add

**Comment by willpote** [comment]
https://github.com/Uniswap/routing-api/commit/67ebc11a02c6d71fc5d4a7489b4ffdb630188443
