### ISSUE TITLE
How to start the current project with localstack tool

### ISSUE THREAD

**Issue by HanHanPecan** [Uniswap/routing-api#34]
I want to start a local service to test the current project, so I tried many methods. There is nothing better than localstack. I studied it, but it is stagnant at present, so I hope to have relevant local test documents. Thank you

**Comment by willpote** [comment]
There is no way to run the API locally. I recommend using https://github.com/Uniswap/smart-order-router instead. You can run it as a CLI, or wrap it into your own localhost server
