### ISSUE TITLE
No Route Found for token

### ISSUE THREAD

**Issue by rileyg98** [Uniswap/routing-api#35]
Issue: Upon trying to swap with the public Uniswap app to Holdenomics token (address 0x1d7e00a59297161d1733897b5add6a382cc6bf2a) the routing API returns no route found. 

Expected behaviour: The API returns a route, as with other tokens.
Actual behaviour: No route found.

When the auto router API is turned off in settings, the V2 LP is found and trades can occur.

**Comment by willpote** [comment]
This was fixed in https://github.com/Uniswap/smart-order-router 
Holdenomics can now be swapped with the API
