### ISSUE TITLE
Auto Router IP Issue - ParaToken "Insufficient liquidity for this trade" 

### ISSUE THREAD

**Issue by CryptoCirca** [Uniswap/routing-api#37]
Uniswap showing "Insufficient liquidity for this trade" 

![image](https://user-images.githubusercontent.com/95563024/154243796-292b90cf-870c-4569-ac79-b0a404810e93.png)

Disable the Auto Router IP and the transaction works as expected.

![image](https://user-images.githubusercontent.com/95563024/154243821-72ff4a3e-5dbd-43c8-b040-c0266faa6649.png)

Contract: 0x32879b5c0fdbc2a81597f019717b412b9d755a09

**Comment by willpote** [comment]
This is fixed now.
